### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by lljdavis** [ashleydavis/internet-speed-test#1]
Followed the process.  Doesn't seem to get value(s) from api function call.   Just wondering if any changes in fast-cli support this solution.

**Comment by ashleydavis** [comment]
Yes there's a problem with it.

Seems to be related to fast-cli.

I've tried updating to latest fast-cli and it didn't help.

Do you have any idea what's going wrong?

**Comment by ashleydavis** [comment]
I got it working. Fast-cli has changed and I had to update to match it.

Thanks for reporting the problem.

**Comment by lljdavis** [comment]
Thanks.   Good job.

Larry Davis
On 1/15/2021 6:33:44 PM, Ashley Davis <notifications@github.com> wrote:
I got it working. Fast-cli has changed and I had to update to match it.
Thanks for reporting the problem.
